#include "pages.h"

String AP404 = "<!DOCTYPE html>"
"<html>"
"   <head>"
"       <title>Not found</title>"
"   </head>"
"   <body>"
"       <h1>404 Not Found</h1>"
"       <p>The requested resource was not found on this device.</p>"
"   </body>"
"</html>";

String APIndex = "<!DOCTYPE html>"
"<html>"
"    <head>"
"        <title>ESP32 Locker</title>"
"    </head>"
"    <body>"
"        <table align=center>"
"            <tr>"
"                <td><h1>ESP32 Locker Setup</h1></td>"
"            </tr>"
"            <tr>"
"                <td><h3>Setup your connection to cloud:</h3></td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <form action=\"/cloudSetup\" method=\"POST\">"
"                        <b>SSID: </b><input type=\"text\" size=\"30\" name=\"SSID\" placeholder=\"Type your WiFi SSID here...\" autocomplete=\"off\" required>"
"                        <p><details>"
"                            <summary><b>What is SSID?</b></summary>"
"                            <b>SSID</b> is simply a symbolyc name of a WiFi Access Point."
"                        </details></p>"
"                        <p><b>Password: </b><input type=\"password\" size=\"30\" name=\"password\" placeholder=\"Type your WiFi password here...\" autocomplete=\"off\" required></p>"
"                        <p><b>Verification code: </b><input type=\"text\" size=\"30\" name=\"dtoken\" placeholder=\"Type your code here...\" autocomplete=\"off\" required></p>"
"                        <p><input type=\"submit\" value=\"Connect to cloud\"/></p>"
"                    </form>"
"                </td>"
"            </tr>"
"            <tr>"
"                <td><h3>Or visit local setup page</h3></td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <form action=\"/localSetup\">"
"                        <input type=\"submit\" value=\"Local Setup\">"
"                    </form>"
"                </td>"
"            </tr>"
"            <tr>"
"                <td><br><br><br><br><br><br></td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <h3>Add a custom server address</h3>"
"                    (Advanced users only!)<br>"
"                    Pay attention that this feature supports only http now."
"                </td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <form action=\"/customServerSetup\" method=\"POST\">"
"                        <b>SSID: </b><input type=\"text\" size=\"30\" name=\"SSID\" placeholder=\"Type your WiFi SSID here...\" autocomplete=\"off\" required>"
"                        <p><b>Password: </b><input type=\"password\" size=\"30\" name=\"password\" placeholder=\"Type your WiFi password here...\" autocomplete=\"off\" required></p>"
"                        <b>IP-address: </b><input type=\"text\" name=\"customIP\" placeholder=\"ex. 127.0.0.1\" minlength=\"7\" maxlength=\"15\" size=\"15\" pattern=\"^((\\d{1,2}|1\\d\\d|2[0-4]\\d|25[0-5])\\.){3}(\\d{1,2}|1\\d\\d|2[0-4]\\d|25[0-5])$\" required>"
"                        <p><b>Port: </b><input type=\"number\" name=\"customPort\" placeholder=\"ex. 8080\" min=\"0\" max=\"65535\" required></p>"
"                        <p><input type=\"submit\" value=\"Connect to custom server\"/></p>"
"                    </form>"
"                </td>"
"            </tr>"
"            <tr>"
"                <td><br><br><br></td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <details>"
"                        <summary><b>Factory reset</b></summary>"
"                        <details>"
"                            <summary><b>Are you sure?</b></summary>"
"                            <b>ALL DATA WILL BE LOST</b><br>"
"                            <form action=\"/factoryReset\" method=\"POST\">"
"                                <input type=\"submit\" value=\"Reset to factory settings.\">"
"                            </form>"
"                        </details>"
"                    </details>"
"                </td>"
"            </tr>"
"        </table>"
"    </body>"
"</html>";

String APConfirmCloudPage = "<!DOCTYPE html>"
"<html>"
"    <head>"
"        <title>Cloud connection</title>"
"    </head>"
"    <body>"
"        <table align=center>"
"            <tr>"
"                <td><h1>Cloud connection setup</h1></td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <b>Now ESP32 will try to connect to your WiFi via SSID and password.</b><br><br>"
"                        In case of failure WiFi connection the yellow led will flash<br>"
"                    and you will be able to do setup again.<br><br>"
"                        In case of failure cloud connection the red led will flash.<br>"
"                    Then check your WiFi Internet connection and contact tech support."
"                </td>"
"            </tr>"
"        </table>"
"    </body>"
"</html>";

String APLocalSetupPage = "<!DOCTYPE html>"
"<html>"
"    <head>"
"        <title>Local setup</title>"
"    </head>"
"    <body>"
"        <table align=center>"
"            <tr>"
"                <td><h1>Local setup</h1></td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <b>Local use is very limited and we strongly recommend to connect to cloud</b><br><br>"
"                        Here is the user manual in FAQ-style for local use:"
"                </td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <details>"
"                        <summary><b>0. How to begin?</b></summary>"
"                        Your system is already working.<br>"
"                        Simply add a new keycard and you're ready to go.<br>"
"                        <b>Please pay attention to paragraph 3 of this FAQ.</b>"
"                    </details>"
"                </td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <details>"
"                        <summary><b>1. How to add a keycard?</b></summary>"
"                        To add a keycard you will need a master card.<br>"
"                        <b>1.</b>Put a maskter card near reader.<br>"
"                        &emsp;You'll hear a sound and yellow led will glow.<br>"
"                        &emsp;You'll now have a minute to add a keycard.<br>"
"                        <b>2.</b>Open doors you want to link to card.<br>"
"                        &emsp;(Keycard is only able to open linked doors)<br>"
"                        <b>3.</b>Put a new keycard you want to add near reader.<br>"
"                        &emsp;After a sound and green led's flash your card is added."
"                    </details>"
"                </td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <details>"
"                        <summary><b>2. How to delete a keycard?</b></summary>"
"                        To delete a keycard you will need a master card.<br>"
"                        Note that your card's number must be already added to delete it.<br>"
"                        <b>1.</b>Put a maskter card near reader.<br>"
"                        &emsp;You'll hear a sound and yellow led will glow.<br>"
"                        <b>2.</b>Put a keycard you want to delete near reader.<br>"
"                        &emsp;After a sound and red led's flash your card is deleted."
"                    </details>"
"                </td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <details>"
"                        <summary><b>3. How to get more secure?</b></summary>"
"                        Note that in case of local use your ESP32 is always in Access Point mode.<br>"
"                        Because every ESP32 has same WiFi SSID and password by default it is<br>"
"                        &emsp;highly recommended to change them.<br>"
"                        (You'll also need to change SSID in case of multiple local devices)"
"                        <form action=\"/changeAPConfig\" method=\"POST\">"
"                            <b>1.</b>Change your device's SSID."
"                            <p><input type=\"text\" size=\"30\" name=\"newSSID\" placeholder=\"Type your new SSID here...\" autocomplete=\"off\"></p>"
"                            <p><b>2.</b>Change your device's password</p>"
"                            <p><input type=\"text\" size=\"30\" name=\"newPassword\" placeholder=\"Type your new password here...\" autocomplete=\"off\" required></p>"
"                            <p><input type=\"submit\" value=\"Change\"/></p>"
"                        </form>"
"                    </details>"
"                </td>"
"            </tr>"
"            <tr>"
"                <td><br><br><br></td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <b>Please note that local use supports only basic functionality and is not very secure.</b>"
"                </td>"
"            </tr>"
"        </table>"
"    </body>"
"</html>";

String APConfirmCustomPage = "<!DOCTYPE html>"
"<html>"
"    <head>"
"        <title>Custom server connection</title>"
"    </head>"
"    <body>"
"        <table align=center>"
"            <tr>"
"                <td><h1>Custom server connection setup</h1></td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    <b>Now ESP32 will try to connect to your WiFi via SSID and password.</b><br><br>"
"                        In case of failure WiFi connection the yellow led will flash<br>"
"                    and you will be able to do setup again.<br><br>"
"                        In case of failure custom server connection the red led will flash.<br>"
"                    Then check your WiFi Internet connection and contact tech support."
"                </td>"
"            </tr>"
"        </table>"
"    </body>"
"</html>";

String APChangeConfigPage = "<!DOCTYPE html>"
"<html>"
"    <head>"
"        <title>Settings change</title>"
"        <meta http-equiv=\"refresh\" content=\"10;URL=/\" />"
"    </head>"
"    <body>"
"        <table align=center>"
"            <tr>"
"                <td><h1>Device's WiFi settings has changed</h1></td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    The device will be rebooted and you'll need to reconnect via WiFi again."
"                </td>"
"            </tr>"
"        </table>"
"    </body>"
"</html>";

String APResetDevicePage = "<!DOCTYPE html>"
"<html>"
"    <head>"
"        <title>Reset device</title>"
"        <meta http-equiv=\"refresh\" content=\"15;URL=/\" />"
"    </head>"
"    <body>"
"        <table align=center>"
"            <tr>"
"                <td><h1>Device's setting and data is reset to factory</h1></td>"
"            </tr>"
"            <tr>"
"                <td>"
"                    Device will be in AP mode with default settings.<br>"
"                    Device's keycard database wiped.<br>"
"                    All bindings to cloud/server cleared."
"                </td>"
"            </tr>"
"        </table>"
"    </body>"
"</html>";